[package]
authors = ["Chun-Kwong Wong <chunkwong.wong@gmail.com>"]
edition = "2018"
name = "rxd"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'

[dependencies]
getopts = "0.2.21"
